version: "3.1"
services:
  # SPRING BOOT APPLICATION
  app:
    image: micasa-api
    container_name: micasa-api-app
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres

  # POSTGRES
  postgres:
    image: postgres:latest
    container_name: micasa-api-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=micasa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
