version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: micasa-api-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=micasa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: