# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
#spring.datasource.url=jdbc:postgresql://ec2-34-233-0-64.compute-1.amazonaws.com:5432/d5i4lacg0pr4r0?sslmode=require
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration